# Welcome to Jekyll!
#

# Site settings
title: Manuel Vigo
description: |
  Design Research and Strategy 
  Page is getting redesigned, as of July 23, 2017
  [Say hello!](mailto:manuel@tacutacu.pe)
owner: Manuel # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: manuel@tacutacu.pe
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manuelvigo.com" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<manuelvigo>
  github: https://github.com/<mvigo>
  linkedin-square: https://linkedin.com/in/<manuel.vigo>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
